---
- name: Create Namespace in K8s 
  hosts: k8s_cluster1
  tasks:
    - name: Expose https port with ClusterIP
      k8s_service:
        state: present
        name: test-https
        namespace: default
        ports:
         - port: 443
           protocol: TCP
        selector:
          key: special

