---
- name: Create Namespace in K8s 
  hosts: k8s_cluster1
  tasks:
    - name: Get an existing Service object
      k8s_facts:
        api_version: v1
        kind: Service
        name: web
        namespace: testing
      register: web_service

    - name: Print object information
      debug:
        var: web_service
